# Site settings
title: Spher
# the subpath baseurl must be to be publish & working in production under spher.ch
# if you want to preview the website under username.github.io/spher, you have to change baseurl to /spher
baseurl: ""
url: "" # the base hostname & protocol for your site
email: ""

# Build settings
markdown: kramdown
exclude: [node_modules, gulp-config.json, Gulpfile.js, package.json, webpack-config.js, package-lock.json, README.md]